== II. Метапрограммирование [1 балл]

На Масленицу подают на стол тарелки с блинами и икрой

[source,cpp]
struct blin {};
struct ikra {};
template<class Sloy1, class... Sloi> struct tarelka {};

Блинов и икры может быть сколько угодно (не менее 1 слоя), но есть физическое ограничение: два слоя икры подряд сделать нельзя (это же получится один толстый слой).

=== Часть 1. Проверка правильности [0.5 балла]

Напишите метафункцию pravilno_v, которая проверяет, правильно ли сформировали стопку блинов и икры

[source,cpp]
template<class Tarelka> constexpr bool pravilno_v = ???;

=== Часть 2. Конструктор тарелки [0.5 балла]

Напишите операцию сложения блинов и икры

[source,cpp]
auto bb = blin{} + blin{};  // tarelka<blin,blin>
auto bi = blin{} + ikra{};  // tarelka<blin,ikra>
auto bii = bi + ikra{};     // невозможно: две икры подряд!
auto ibi = ikra{} + bi;     // tarelka<ikra,blin,ikra>
auto bibb = bi + bb;        // tarelka<blin,ikra,blin,blin>
auto biibi = bi + ibi;      // невозможно: две икры подряд

Ошибка двойной икры должна быть сделана как SFINAE (не найдётся перегрузка оператора), а не как безусловная ошибка компиляции (например, static_assert внутри). Это нужно для тестирования.

Обратите внимание, что из-за ассоциативности операции сложения операндами и слева и справа могут оказаться и отдельный блин или икра, и тарелки.
