= Семинар 4.
:icons: font
:lecture: Лекция 2
:table-caption!:
:example-caption!:
:source-highlighter: highlightjs
:revealjs_hash: true
:customcss: https://rawcdn.githack.com/fedochet/asciidoc-revealjs-online-converter/7012d6dd12132363bbec8ba4800272ceb6d0a3e6/asciidoc_revealjs_custom_style.css
:revealjs_theme: blood
:stylesheet: main.css

== Вопросы по предыдущему семинару

???

== Вопросы по контрольной

???

== Hands on protobuf

* Установим и соберём https://github.com/protocolbuffers/protobuf/releases/tag/v3.15.6[последний релиз]
* Собираем симейком
- https://github.com/protocolbuffers/protobuf/blob/master/cmake/README.md[мануал для windows]
- Для линуксов: `cd cmake && mkdir build && cd build && make -j <число ядер у вас> && make install`
* если хотите для питона, тоже можно либо собрать, либо `pip install --upgrade protobuf`


ifdef::backend-revealjs[=== !]

Что теперь делаем

[%step]
* Каждый клонирует общественно доступный (только внутри сообщества cpp курса) https://github.com/cpp-practice/cpp-classroom-2021-sem02-cls04-in-class[репозиторий]
* вызываем добровольца определить .proto структуру, описывающую студента: можем пофантазировать, но как минимум хочется про каждого участника узнать его имя, фамилию, гитхаб-логин и ~~пинкод от кредитки~~
* также нам потребуется структура для базы данных студентов (в нашем случае просто список)

ifdef::backend-revealjs[=== !]

* синкаем репозиторий, и все самостоятельно пишем код, который
- загрузит текущую базу данных со студентами, **если она уже есть** (договоримся хранить её в корне репозитория в файлике `students_db.bin`)
- добавит в неё себя (**если ещё не добавлен**)
- и сериализует заново туда же в `students_db.bin`

ifdef::backend-revealjs[=== !]
* Как написали код и обновили бинарную базу данных, пушим результат в общий репозиторий
* Кто затрёт нам базу данных или зальет в неё мусор - минус балл и отчисление
* Если будут конфликты, рибейзимся красиво и правильно, как петербуржцы.

== Задачка 1: CowJson [2 балла]

В этой задачке вам предлагается реализовать класс CowJson, позволяющий работать с json-объектами в с++.

Название класса конечно не случайно, и дело тут не только в нашей любви к коровам: `CowJson` должен поддерживать copy-on-write семантику, то есть,
избегать лишних копирований, пока это не требуется [подробнее про критерии "когда это не требуется" дальше].

ifdef::backend-revealjs[=== !]

`CowJson` - шаблонный класс с параметрами-шаблонами `Map` и `Array`.

* `Map` будет использоваться для реализации `CowJson` объекта a-la словарь
* `Array` - для json массивов
* По дефолту в качестве Map должна быть `std::map`, в качестве `Array` - `std::vector`.

С точки зрения грамматики, `CowJson` определяется так:

`CowJson := [nullptr|bool|int|double|Map<std::string,CowJson>|Array<CowJson>]`

ifdef::backend-revealjs[=== !]

CowJson должен поддерживать также следующие методы

* неявные конструкторы от любого из перечисленных выше типов (`nullptr`,`bool`,`int`...)
- конструктор от `std::initializer_list` поддерживать не требуется, но если хотите - поддержите
* конструкторы копирования / перемещения

ifdef::backend-revealjs[=== !]

* операторы присваивания от этих же типов + конечно от `CowJson` (move/copy)
- при копировании `CowJson` должен вести себя лениво и не копировать всю древовидную структуру (в этом суть cow)

ifdef::backend-revealjs[=== !]

* шаблонные методы
- `T& get<T>()` где `T` - один из типов, перечисленных выше
- `const T& get<T>() const` где `T` - один из типов, перечисленных выше
- `const T& cget<T>() const` ...

ifdef::backend-revealjs[=== !]

Во всех случаях, если `CowJson`, на котором вызван метод `get/cget` хранит тип, отличный от запрошенного,
он **бросает исключение** типа `CowJsonBadAccess` (уже определён в cowjson.hpp).

Стоит обратить внимание на неконстантный метод get: так как он возвращает неконстантную lvalue-ссылку на хранимый объект,
дальнейшая судьба объекта оказывается в руках пользователя, поэтому в этот момент мы хотим пессимистично заранее выполнить copy в случае,
если изменение отданного объекта может кого-то зааффектить кроме текущего узла.

* шаблонный константный метод `is<T>`, проверяющий, хранит ли узел тип `T`, где `T` - один из `[nullptr|bool|int|double|Map<std::string,CowJson>|Array<CowJson>]`


ifdef::backend-revealjs[=== !]

* должны быть объявлены публичные псевдонимы типов `dict` и `array` внутри `CowJson`

ifdef::backend-revealjs[=== !]

* конечно, плох тот json, который нельзя сериализовать в строку и десериализовать из неё. Правда, мы привыкли работать не со строками, а с потоками ввода вывода, поэтому просим вас написать две функции
- `static CowJson CowJson::restore(std::istream& in);` (считаем, что пробелов в сериализованном json нет; также можно забить (считать, что такого не будет) на спецсимволы внутри строк типа кавычек).
- `void CowJson::dump(std::ostream& out) const;` (с правилами сериализации можете ознакомиться в смоук тестах, они в целом стандартные для json)

ifdef::backend-revealjs[=== !]

* добавьте также два свободных оператора-друга `>>` и `<<` для того, чтобы работало как привычно `in >> json;` и `out << json;`


Разбалловка: всё до сериализации-десериализации стоит 1 балл, сериализация-десериализация ещё 1 балл (каждая по 0.5). Вторая часть без первой не особо имеет смысл, так что рекомендуется начинать решать в естественном порядке.

Решение должно быть реализовано в пространстве имён `cls_04`.

== Задачка 2: Testing Calculate [2 балла]

Тут всё совсем просто: даже код писать не нужно. Ну, почти... Нашей целью будет покрытие тестами некоторой функции, имеющей сигнатуру

[source,cpp]
----
// вычисляет переданное в строке выражение по стандартным правилам арифметики
// находится в глобальном пространстве имён
double calculate(const std::string& expression);

// кидается когда что-то при выполнении calculate идёт не так
class calculate_exception : public std::exception {};
----

ifdef::backend-revealjs[=== !]

По заявлению авторов, `calculate` это очень хорошая функция. Она

* умеет работать с базовыми арифметическими операциями +-*/
* поддерживает скобки
* умеет игнорировать пробелы (символы ' ') в переданной строке
* понимает дробные числа как в обычной форме (123.456) так и в научной (6.67e-23). В научной нотации `e` может быть и маленькой, и большой!
* поддерживает унарный + и унарный - (при этом выражение ---2 например cчитается корректным - по правилу минус на минус даёт плюс)
* Поэкспериментировать с *более менее* корректной реализацией `calculate` вы можете, собрав таргет calc из этого репозитория (будьте бдительны, там голый СИ!)


ifdef::backend-revealjs[=== !]
Примеры запусков calculate:

[source,cpp]
----
calculate("") // бросает исключение типа calculate_exception
calculate("1/0") // бросает исключение типа calculate_exception
calculate("()") // бросает исключение типа calculate_exception
calculate("1") // вернет 1
calculate("1 + 2") // вернет 3 (обратите внимание, пробелы не поломали calculate!)
calculate("(1 + 2) * 3") // вернет 9, скобки работают!
----


ifdef::backend-revealjs[=== !]
Про ошибки: утверждается, что calculate обрабатывает все некорректные входные данные единообразно: кидает исключение типа `calculate_exception`

ifdef::backend-revealjs[=== !]

От вас требуется оформить своё решение в виде одного (или более) gtest test-case в файле test_calculate.cpp.
В закрытом репозитории будет размещен набор реализаций calculate разной степени хорошести, которые ваши тесты должны по возможности поломать (то есть убедиться
в несоответствии реализации и спецификации как можно большего числа реализаций)

(sic!) Для этой задачи правило про бонусный дедлайн не работает.
